In [1]:
#question1
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    return numpy.array(arr[::-1],dtype='float')
    
    
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [2]:
#question2
import numpy




arr = input().strip().split(' ')
arr=numpy.array(arr,dtype='int')
print (numpy.reshape(arr,(3,3)))





1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#question3
import numpy




n, m = map(int, input().split())
x = numpy.array([input().strip().split() for _ in range(n)], int)
print(x.transpose())
print(x.flatten())





2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [4]:
#question4
import numpy


x = input().split()
n = numpy.array([input().split() for i in range(int(x[0]))], dtype='int')
m = numpy.array([input().split() for i in range(int(x[1]))],dtype='int')

print(numpy.concatenate((n, m)))



4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [5]:
#question5
import numpy



x=list(map(int,input().split()))
print(numpy.zeros(x,dtype ='int'))
print(numpy.ones(x,dtype = 'int'))
    


3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [16]:
#question6
import numpy
numpy.set_printoptions(sign=' ')
x=list(map(int, input().split()))
print(numpy.eye(x[0],x[1]))


3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [6]:
#question7
import numpy
n= list(map(int,input().split()))

x = numpy.array([list(map(int, input().split())) for _ in range(n[0])], int)
y = numpy.array([list(map(int, input().split())) for _ in range(n[0])], int)
    

print (numpy.add(x,y))
print (numpy.subtract(x,y))
print (numpy.multiply(x,y,))
print (numpy.floor_divide(x,y))
print (numpy.mod(x,y))
print (numpy.power(x,y))




1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [7]:
#question8
import numpy

numpy.set_printoptions(sign=' ')

x = numpy.array(input().split(), float)
print (numpy.floor(x))
print (numpy.ceil(x))
print (numpy.rint(x))


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [8]:
#question9
import numpy

x= list(map(int, input().split()))

y = numpy.array([input().split() for i in range(x[0])], int)

z=numpy.sum(y, axis = 0)

print(numpy.prod(z, axis = None))


2 2
1 2
3 4
24


In [10]:
#question10
import numpy



x = list(map(int, input().split()))

y = numpy.array([input().split() for _ in range(x[0])],dtype = int)

print(numpy.max(numpy.min(y, axis=1), axis=0))


4 2
2 5
3 7
1 3
4 0
3


In [11]:
#question11
import numpy





x = list(map(int, input().split()))


y = numpy.array([input().split() for _ in range(x[0])],dtype = int)

print(numpy.mean(y, axis =1))
print(numpy.var(y, axis =0))
print(numpy.round(numpy.std(y, axis = None),11))



2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [12]:
#question12
import numpy



n = int(input())

x = numpy.array([input().split() for _ in range(n)], dtype =int)
y = numpy.array([input().split() for _ in range(n)], dtype =int)
z = numpy.dot(x,y)
print(z)


2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [13]:
#question13
import numpy




x = numpy.array(input().split() , int)
y = numpy.array(input().split() , int)
print(numpy.inner(x, y))
print(numpy.outer(x, y))


0 1
2 3
3
[[0 0]
 [2 3]]


In [14]:
#question14
import numpy
m = numpy.array(input().split(), float)
n = float(input())
print(numpy.polyval(m, n))


1.1 2 3
0
3.0


In [15]:
#question15
import numpy





numpy.set_printoptions(legacy='1.13')

n = int(input())
x= numpy.array([input().split() for i in range(n)], float)
print(numpy.linalg.det(x))


2
1.1 1.1
1.1 1.1
0.0
